@startuml
actor User

participant "HUD" as HUD
participant "Controller/Input Manager" as Input
participant "Room Manager" as Room
participant "Auth Manager" as Auth
participant "Art Tools Manager" as Tools
participant "Network Manager" as Network
participant "Event Logger" as Event

User -> HUD : User selects "Customise gallery"
HUD -> Input : Listen to input
Input -> Auth : Check permissions

alt User authorised
  Auth -> Input : Reply with permissions
  Input -> Room : Reply with permissions

  loop For each customisation
    Room -> Tools : Initialise tools
    Tools -> Room : Forward tools to display
    Room -> HUD : Forward loaded workspace with tools
    HUD -> User : Display workspace with tools
    User -> Input : Select a tool
    Input -> Room : Log selected tool
    Room -> Tools : Request functionality
    Tools -> Input : Provide functionality
    Input -> HUD : Display tool functionality
    User -> Input : Select action
    Input -> Network : Save the action

    alt Log successful
      Network -> Event : Saved
      Network -> Room : Saved
    else Log unsuccessful
      Network -> Event : Unsaved
      Network -> Room : Tool usage not saved
      Room -> HUD : Saving error
      HUD -> User : Display 'Error: Customisation not saved'
    end
  end
else User unauthorised
  Auth -> HUD : Send failed request
  HUD -> User : Display "Access not permitted"
end
@enduml
